name: Delete Merged Branch

on:
  pull_request:
    types: [closed]

jobs:
  delete-branch:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    permissions:
      contents: write
    
    steps:
    - name: Delete merged branch
      uses: actions/github-script@v7
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        script: |
          const { owner, repo } = context.repo;
          const branch = context.payload.pull_request.head.ref;
          const headRepoOwner = context.payload.pull_request.head.repo?.owner?.login;
          
          // Only delete branches from the same repository
          if (headRepoOwner === owner) {
            try {
              await github.rest.git.deleteRef({
                owner: owner,
                repo: repo,
                ref: `heads/${branch}`
              });
              console.log(`✅ Successfully deleted branch: ${branch}`);
            } catch (error) {
              // Branch might already be deleted or protected
              if (error.status === 422 || error.status === 404) {
                console.log(`ℹ️  Branch ${branch} is protected or already deleted`);
              } else {
                throw error;
              }
            }
          } else {
            console.log(`ℹ️  Skipping deletion of branch from fork: ${headRepoOwner}/${branch}`);
          }